In [5]:
import requests
import json
import csv
import pandas

from datetime import datetime

# Constants
number_of_contacts = 9000
records_per_query = 100
postcode_table = pandas.DataFrame({'SiteName':["Wimbletech","TheWorkary - Chiswick","Rivertech","TheWorkary - Brompton","TheWorkary - NottingHill","TheWorkary - Hanwell","TheWorkary - Chelsea","TheWorkary - Welling","TheWorkary - Caterham","TheWorkary - Maidenhead", "TheWorkary - Barnet Pop Up","TheWorkary - Avonmore","TheWorkary - Rainham"],'SitePostcode':["SW197NB","W42AB","WD31HP","SW50BS","W24EW","W71PD","SW35EZ","DA163PA","CR36TR","SL61JX",None,"W148TG","RM139YJ"]})
# Documentation
# https://developers.activecampaign.com/reference#pagination
# 
# Point to the Active Campaign Table and Request All Date 

def retrieve_all_contacts(global_list_object):
  url = "https://wimbletech.api-us1.com/api/3/contacts"
  for counter in range(number_of_contacts/100):
    headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
    querystring = {"status":"-1","limit": records_per_query,"offset": records_per_query*counter}
    response = requests.request("GET", url, headers=headers, params=querystring)
    contacts_output = json.loads(response.text)["contacts"]
    print(querystring)
    global_list_object = global_list_object + contacts_output
    
    #Introduce Rate Limits
    if(counter+1 % 5 == 0):
      print("Pause for Rate-Limit")
      sleep(2)
      console.log("Pause for Rate-Limit")

    # Write To File
  with open('names.csv', 'w', newline='') as csvfile:
    print("Field Names = " + str(contacts_db[0].keys()))
    fieldnames = contacts_output[0].keys()

    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()

    for item in contacts_db:
      writer.writerow(item)
      sleep(0.5)

def retrieve_all_field_values(global_list_object):
  for counter in range(number_of_contacts/100):
    field_values_url = "https://wimbletech.api-us1.com/api/3/fieldValues"
    headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
    querystring = {"status":"-1","limit": records_per_query,"offset": records_per_query*counter}
    response = requests.request("GET", field_values_url, headers=headers, params=querystring)
    contacts_output = json.loads(response.text)["contacts"]
    print(querystring)
    global_list_object = global_list_object + contacts_output
      
    #Introduce Rate Limits
    if(counter+1 % 5 == 0):
      print("Pause for Rate-Limit")
      sleep(2)
      console.log("Pause for Rate-Limit")

    # Write To File
    with open('fieldnames.csv', 'w', newline='') as csvfile:
      print("Field Names = " + str(contacts_db[0].keys()))
      fieldnames = contacts_output[0].keys()

      writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

      writer.writeheader()

      for item in contacts_db:
        writer.writerow(item)
        sleep(0.5)

def retrieve_field_values(id):
  url = "https://wimbletech.api-us1.com/api/3/fieldValues/" + str(id)
  headers = {"Accept": "application/json"}
  headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
  querystring = {"status":"-1","limit": records_per_query,"offset": records_per_query*counter}
  response = requests.request("GET", url, headers=headers, params=querystring)
  print(response.text)

def retrieve_field_values_2():
  url = "https://wimbletech.api-us1.com/api/3/fields"

  querystring = {"limit":"1"}
  headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
  response = requests.request("GET", url, headers=headers, params=querystring)
  print(response.text)

def retrieve_all_lists():
  url = "https://wimbletech.api-us1.com/api/3/lists"
  headers = {"Accept": "application/json"}
  response = requests.request("GET", url, headers=headers)
  print(response.text)

def print_only_completed_results():
  df = pandas.read_csv('/content/Active Campaign - Contacts Report.csv',dtype='unicode')
  print(len(df))
  print(len(df.columns))

  # Select Only Desired Columns
  df2_only_desired_columns = df.iloc[:,[0,1,2,3,12,17,19,25,52,54,60,79,100]]
  # Drop Any Columns with Any Missing Rows
  return df2_only_desired_columns.dropna()

def print_only_complete_records():
  df = pandas.read_csv('/content/Active Campaign - Contacts Report.csv')
  print(len(df))
  print(len(df.columns))

  # Select Only Desired Columns
  df2_only_desired_columns = df.iloc[:,[0,1,2,3,12,17,19,25,52,54,60,79,100]]
  print(df2_only_desired_columns.columns)
  # Drop Any Columns with Any Missing Rows
  return df2_only_desired_columns.dropna()

def produce_data_frame():
  df = pandas.read_csv('Active Campaign - Contacts Report.csv',dtype='unicode')
  print(len(df))
  print(len(df.columns))

  # # Tapi.postcodes.io/postcodes/
  url = https://wimbletech.api-us1.com/api/3/contacts?api_key=03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0&include=fieldValues
  # field_values_url = "https://api.postcodes.io/postcodes/"
  # headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
  # querystring = {"status":"-1","limit": records_per_query,"offset": records_per_query*counter}
  # response = requests.request("GET", field_values_url, headers=headers, params=querystring)
  # contacts_output = json.loads(response.text)["contacts"]
  
    
  # Select Only Desired Columns
  df2_only_desired_columns = df.iloc[:,[0,1,2,3,12,17,19,25,52,54,60,79,100]]
  
  # Create Value Counts For Each Site
  df2_site_counts = df2_only_desired_columns['*Venue - Site (final)'].value_counts().to_frame()
  print(df2_site_counts.columns)

  # Merge Aggregated Count Table with Original Table
  df3_merged_table = df2_only_desired_columns.merge(df2_site_counts,how='outer',left_on='*Venue - Site (final)',right_index=True)
  
  # Merge Post-Codes On To Table
  df4_postcode_included_table = df3_merged_table.merge(postcode_table,how='outer',left_on='*Venue - Site (final)',right_on="SiteName")

  # Insert Flag Columns for Null Values
  df4_postcode_included_table['LastDateIncluded'] = df4_postcode_included_table['*Last Date'].notnull()
  df4_postcode_included_table['StartDateIncluded'] = df4_postcode_included_table['*Start Date'].notnull()
  # df4_postcode_included_table['VenueSiteFinalIncluded'] = df4_postcode_included_table['*Venue - Site (final)'].notnull()
  # df4_postcode_included_table['PostcodeIncluded'] = df4_postcode_included_table['*Postcode'].notnull()

  # Incorporate Straight Line Distance
  # Retrieve A List of All Postcodes in Our Database
  # https://postcodes.io/
  # api.postcodes.io/postcodes

  # Could Add In Prospect / Member Live Field If Possible
  # Could Add in Location Information
  # Write Search Queries That Return Filtered Fields for Dates Within Different Time Regions < 30 days >

  # Output the file
  df4_postcode_included_table.filter(items=["SitePostcode","*Postcode"]).to_csv('PostcodeBank.csv',index=False)
  # Drop Any Columns with Any Missing Rows
  return df4_postcode_included_table

def printout_contacts_report(dataframe):
  df = pandas.read_csv('/Active Campaign - Contacts Report.csv',dtype='unicode')
  print(len(df))
  print(len(df.columns))

  # Select Only Desired Columns
  df2_only_desired_columns = df.iloc[:,[0,1,2,3,12,17,19,25,52,54,60,79,100]].sort_values(['*Last Date'])
  # Create Additional Flag Fields Indicating Nan Values
  df2_nan_flags = df2_only_desired_columns.isna()

  return df2_only_desired_columns
  # Conduct A Grouped Count Of How Many Members Are In Samples For Each Column (After Excluding Nulls)
    # Where Start Date Is Before Today and L
  above_35 = dataframe[dataframe["*Start Date"] > 35]

  # Conduct A Grouped Count Of How Many Members Are In Samples For Each Column (Non-Nulls Group By Sites)

  # Conduct A Count Of Start Dates In The Future
    # 1. List Of New Starter Members - Where Start Date Is After Today
    # 2. Count Of New Starter Members By Site - Where Start Date Is After Today Grouped By Site
  # Conduct A Count of Start Dates In The Last 30 Days
    # 3. Count Of New Starter Members By Site - Where the Start Date Is Within the Last 30 Days
    # 4. Count Of New Starter Members By Site - Where the Start Date Is Within The Last 30 Days - Grouped By Site
  # Conduct A Count of Leaving Dates In The Next 30 Days
    # 5. Count Of New Starter Members By Site - Where the Leave Date Is Within The Next 30 Days
    # 6. Count Of New Starter Members By Site - Where the Start Date Is Within The Next 30 Days - Grouped By Site
  # Conduct A Count of Start Dates In The Pass 90 Days
    # 7. Count Of New Starter Members By Site - Where the Start Date Is Within The Next 90 Days
    # 8. Count Of New Starter Members By Site - Where the Start Date Is Within The Next 90 Days - Grouped By Site=
  
  # Historical Data Analytics
  # Membership Duration Time - Length Of Stay
  # Conduct A Count of Postcode 

produce_data_frame()
# url = "https://wimbletech.api-us1.com/api/3/contacts/12569"
# querystring = {}
# headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
# querystring = {"limit": 1}
# response = requests.request("GET", url, headers=headers,params=querystring)
# contact = json.loads(response.text)
# print(contact['contactAutomations'])

# url = "https://wimbletech.api-us1.com/api/3/activities"
# querystring = {}
# headers = {"Accept": "application/json","Api-Token":"03607701a84655ffeffb618671d5f4be937c574b9bf1fe11ad19b157b1aef835d90768f0"}
# response = requests.request("GET", url, headers=headers, params=querystring)
# activities_output = json.loads(response.text)

# print("OUTPUT META")
# with open("output", "w") as outfile:
#     outfile.write(str(json.loads(response.text)))


#json_response = json.loads(response.text)

# Objective is a Visualisation of Churn
# e.g Users Who Are Currently Members
# e.g Users Who Are Leaving
# e.g Users

# print(json_response)
# for item in json_response["contacts"]:
#   if item["firstName"] and item["lastName"]:
#     print(item["firstName"] + " " + item["lastName"])

8984
251
Index(['*Venue - Site (final)'], dtype='object')

,*Venue - Site (final),ID,Email,First Name,Last Name,*Title,*Venue - Site (Preference),*D.O.B.,*Postcode,*Venue - Site (final)_x,*Last Date,*Last Month,*Start Date,*Tour Date,*Venue - Site (final)_y,SiteName,SitePostcode,LastDateIncluded,StartDateIncluded
0,Rivertech,12569,NaN,Vikram,Chudasama,Mr,Rivertech (BasingHouse - Rickmansworth),NaN,NaN,Rivertech,NaN,NaN,2021-05-04,2021-04-26,139.0,Rivertech,WD31HP,False,True
1,Rivertech,997,abbey.robinson@stacktechnology.co.uk,Abbey,Robinson,NaN,NaN,NaN,NaN,Rivertech,2017-10-31,October,NaN,NaN,139.0,Rivertech,WD31HP,True,False
2,Rivertech,5209,abhay.shah@caremark.co.uk,Abhay,Shah,Mr,NaN,NaN,HP52DA,Rivertech,NaN,NaN,2020-08-01,NaN,139.0,Rivertech,WD31HP,False,True
3,Rivertech,4418,abhayshah@hotmail.co.uk,Abhay,Shah,Mr,Rivertech (BasingHouse - Rickmansworth),NaN,NaN,Rivertech,NaN,NaN,2020-01-06,2019-09-27,139.0,Rivertech,WD31HP,False,True
4,Rivertech,4176,accounts@ipcomms.eu,Carel,Solomon,Mr,NaN,NaN,NaN,Rivertech,NaN,NaN,2019-08-01,NaN,139.0,Rivertech,WD31HP,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8980,TheWorkary - Rainham,164,hands4healing@uwclub.net,Diane,Tyrrell,Mrs,Interest in new sites - Rainham,2016-01-23,NaN,TheWorkary - Rainham,2017-06-30,June,2016-01-09,NaN,6.0,TheWorkary - Rainham,RM139YJ,True,True
8981,TheWorkary - Rainham,368,lucie@opalcontracts.co.uk,Lucie,Reeve,Mrs,Rainham - Fixed Single Desk -,1991-06-26,B7 4TE,TheWorkary - Rainham,2017-06-30,June,2016-01-11,NaN,6.0,TheWorkary - Rainham,RM139YJ,True,True
8982,TheWorkary - Rainham,228,mark@mmadvertising.co.uk,Mark,Jones,Mr,Interested in new sites COMING SOON - see belo...,1985-10-22,NaN,TheWorkary - Rainham,2017-06-30,June,2016-05-07,NaN,6.0,TheWorkary - Rainham,RM139YJ,True,True
8983,TheWorkary - Rainham,259,mattmounsey@live.co.uk,Matt,Mounsey,Mr,Rainham - Flexi Desk -,1981-09-22,legal,TheWorkary - Rainham,2017-02-14,February,2016-10-08,NaN,6.0,TheWorkary - Rainham,RM139YJ,True,True
8984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TheWorkary - Barnet Pop Up,None,False,False